<?php

	define('PLUGIN_FLOODCONTROL_POST_LIMIT', 0);
	define('PLUGIN_FLOODCONTROL_POST_PERIOD', 'HOUR');
	define('PLUGIN_FLOODCONTROL_COMMENT_LIMIT', 0);
	define('PLUGIN_FLOODCONTROL_COMMENT_PERIOD', 'HOUR');
		